### ISSUE TITLE
添加依赖后build失败,是否是因为使用了android.support 库

### ISSUE THREAD

**Issue by VishvaWang** [zhouteng0217/ShareExtend#10]
The Gradle failure may have been because of AndroidX incompatibilities in this Flutter app.
See https://goo.gl/CP92wY for more information on the problem and how to fix it.

**Comment by zhouteng0217** [comment]
我这个库里面android的support的库，升级为androidx的库了，你那边的flutter项目里面可能还是用的support包，所以造成了不兼容

**Comment by VishvaWang** [comment]
好的.感谢作者.
