### ISSUE TITLE
Unhandled Exception: MissingPluginException(No implementation found for method share on channel share_extend)

### ISSUE THREAD

**Issue by JayFwj** [zhouteng0217/ShareExtend#14]
Unhandled Exception: MissingPluginException(No implementation found for method share on channel share_extend)
#0      MethodChannel.invokeMethod 
package:flutter/…/services/platform_channel.dart:314
<asynchronous suspension>
#1      ShareExtend.share  (package:share_extend/share_extend.dart:37:21)
#2      MallPDetailNavBarView.build.<anonymous closure> 
package:Flutter/…/detail/MallPDetailNavView.dart:24
#3      _InkResponseState._handleTap 
package:flutter/…/material/ink_well.dart:635
#4      _InkResponseState.build.<anonymous closure> 
package:flutter/…/material/ink_well.dart:711
#5      GestureRecognizer.invokeCallback 
package:flutter/…/gestures/recognizer.dart:182
#6      TapGestureRecognizer._checkUp 
package:flutter/…/gestures/tap.dart:365
#7      TapGestureRecognizer.handlePrimaryPointer 
package:flutter/…/gestures/tap.dart:275
#8      PrimaryPointerGestureRecognizer.handleEvent 
package:flutter/…/gestures/recognizer.dart:455
#9      PointerRouter._dispatch 
package:flutter/…/gestures/pointer_router.dart:75
#10     PointerRouter.route 
package:flutter/…/gestures/pointer_router.dart:102
#11     _WidgetsFlutterBinding&BindingBase&GestureBinding.handleEvent 
package:flutter/…/gestures/binding.dart:218
#12     _WidgetsFlutterBinding&BindingBase&GestureBinding.dispatchEvent 
package:flutter/…/gestures/binding.dart:198
#13     _WidgetsFlutterBinding&BindingBase&GestureBinding._handlePointerEvent 
package:flutter/…/gestures/binding.dart:156
#14     _WidgetsFlutterBinding&BindingBase&GestureBinding._flushPointerEventQueue 
package:flutter/…/gestures/binding.dart:102
#15     _WidgetsFlutterBinding&BindingBase&GestureBinding._handlePointerDataPacket 
package:flutter/…/gestures/binding.dart:86
#16     _rootRunUnary  (dart:async/zone.dart:1136:13)
#17     _CustomZone.runUnary  (dart:async/zone.dart:1029:19)

**Comment by zhouteng0217** [comment]
@JayFwj  Did you build your owner aar library for android or framework library for ios with flutter code?  
If so, you also need add the ```share_extend.aar``` which build on android platform to your project, or  ```ShareExtendPlugin.h  ShareExtendPlugin.m```  on ios platform.
Hope it can help.

**Comment by JAICHANGPARK** [comment]
I had same error

```

E/MethodChannel#share_extend( 7427): java.lang.NullPointerException: Attempt to invoke virtual method 'android.content.res.XmlResourceParser android.content.pm.ProviderInfo.loadXmlMetaData(android.content.pm.PackageManager, java.lang.String)' on a null object reference
E/MethodChannel#share_extend( 7427): 	at androidx.core.content.FileProvider.parsePathStrategy(FileProvider.java:605)
E/MethodChannel#share_extend( 7427): 	at androidx.core.content.FileProvider.getPathStrategy(FileProvider.java:579)
E/MethodChannel#share_extend( 7427): 	at androidx.core.content.FileProvider.getUriForFile(FileProvider.java:417)
E/MethodChannel#share_extend( 7427): 	at com.zt.shareextend.ShareUtils.getUriForFile(ShareUtils.java:30)
E/MethodChannel#share_extend( 7427): 	at com.zt.shareextend.ShareExtendPlugin.share(ShareExtendPlugin.java:84)
E/MethodChannel#share_extend( 7427): 	at com.zt.shareextend.ShareExtendPlugin.onMethodCall(ShareExtendPlugin.java:51)
E/MethodChannel#share_extend( 7427): 	at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler.onMessage(MethodChannel.java:222)
E/MethodChannel#share_extend( 7427): 	at io.flutter.embedding.engine.dart.DartMessenger.handleMessageFromDart(DartMessenger.java:96)
E/MethodChannel#share_extend( 7427): 	at io.flutter.embedding.engine.FlutterJNI.handlePlatformMessage(FlutterJNI.java:643)
E/MethodChannel#share_extend( 7427): 	at android.os.MessageQueue.nativePollOnce(Native Method)
E/MethodChannel#share_extend( 7427): 	at android.os.MessageQueue.next(MessageQueue.java:326)
E/MethodChannel#share_extend( 7427): 	at android.os.Looper.loop(Looper.java:181)
E/MethodChannel#share_extend( 7427): 	at android.app.ActivityThread.main(ActivityThread.java:7045)
E/MethodChannel#share_extend( 7427): 	at java.lang.reflect.Method.invoke(Native Method)
E/MethodChannel#share_extend( 7427): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
E/MethodChannel#share_extend( 7427): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:965)
```

How to Fix This problem?? 

Thanks

**Comment by zhouteng0217** [comment]
@JAICHANGPARK this may happen when the authority of FileProvider in xml not same as the authority used in java code, but this should not happen. I can't figure out how that happened according the log above. Does the example code work well ?

**Comment by JAICHANGPARK** [comment]
@zhouteng0217  Example code works well

**Comment by d-apps** [comment]
I had this problem, solved doing flutter clean then get packages, upgrade packages, and it worked.
