### ISSUE TITLE
Share fileBytes directly

### ISSUE THREAD

**Issue by VadimOsovsky** [zhouteng0217/ShareExtend#15]
When I share a file which is located on some cloud like s3, I have to download, create a file write the bytes to it and only then share it. That's acceptable, however I can't find a way to delete the file after the sharing has been complete.

Please, add a way to send file bytes directly
or
Please, make the future resolve after a file has been already shared so I can safely delete it without setting up background tasks to do it.

**Comment by zhouteng0217** [comment]
This plugin just providers a simple way to share data by calling the sharing mechanism built into Android and IOS systems. It can not do more customized things that the api did not provider.

Maybe some other way to delete the caches, such as delete the caches every time the app starts or exits.

**Comment by VadimOsovsky** [comment]
ok, I'll try to find some other way to do that
