### ISSUE TITLE
Add option to specify "title" for the shared resource

### ISSUE THREAD

**Issue by ekuleshov** [zhouteng0217/ShareExtend#19]
Please add option to specify "title" for the shared resource, e.g. email subject line.

**Comment by kw2019ltd** [comment]
waiting for it

**Comment by zhouteng0217** [comment]
@ekuleshov @kw2019ltd The feature has been added in version 1.1.1.  Please have a try, and thanks for the suggestion.

**Comment by kw2019ltd** [comment]
hi, tried it and give a title still image sent without title i think better to check it again ver 1.1.1

**Comment by zhouteng0217** [comment]
@kw2019ltd  I added the subject field for the sharing，but not all apps support this.
It depends on whether third-party apps use the subject to show.  Tested on email and it worked well, but other apps may not.

**Comment by Adem68** [comment]
Hi @zhouteng0217,

Can you add subject option to shareMultiple function? If you want I can fork then send pr.

**Comment by zhouteng0217** [comment]
@Adem68 , I will add the code for share multiple function in the new version this time. It is just a simple code. Of course PR is always welcome.

**Comment by Adem68** [comment]
You can close this issue. Thanks for reply.
