### ISSUE TITLE
Can we share pdf file?

### ISSUE THREAD

**Issue by snehil2112** [zhouteng0217/ShareExtend#20]
If we can share pdf could you please give a code sample?

**Comment by marcos930807** [comment]
ShareExtend.share(pathToPDF , "file");

**Comment by snehil2112** [comment]
Android dependency 'androidx.lifecycle:lifecycle-runtime' has different version for the compile (2.0.0) and runtime (2.1.0) classpath. You should manually set the same
version via DependencyResolution

getting this error

**Comment by marcos930807** [comment]
Migrate your project to use androidx features.
