### ISSUE TITLE
分享失败，多图分享提示仅支持照片格式。这是为什么？

### ISSUE THREAD

**Issue by chaowen0668** [zhouteng0217/ShareExtend#23]
华为手机。8.0  用demo测试也是提示这个错

**Comment by zhouteng0217** [comment]
@chaowen0668  是不是分享到微信？ 我在测试的过程中，也发现过这个问题，在应用沙盒内的图片，以多图的方式分享到微信有这个问题，分享到qq没问题。我觉得是微信没适配的原因。

 我在demo里面，用到了第三方的支持多图的图库选择插件，它里面获取的图片没有给图片路径，因此只好把图片数据存到沙盒里面，用于来分享测试。

如果要分享的图片路径不是在当前app的应用沙盒内，而是在比如相册，sdcard目录等等，也是可以以多图的形式，成功分享到微信的，但是应用沙盒内的路径就不行，所以我觉得应该是微信的适配问题。
