### ISSUE TITLE
我在分享图片的时候有时候会走三个阶段，前两次都失败，分别显示该文件不存在和该文件为无效文件，然后第三次就成功了，也没有出现报错，请问是问什么，该怎么解决

### ISSUE THREAD

**Issue by 54lianxi** [zhouteng0217/ShareExtend#25]
我在分享图片的时候有时候会走三个阶段，前两次都失败，分别显示该文件不存在和该文件为无效文件，然后第三次就成功了，也没有出现报错，请问是问什么，该怎么解决

**Comment by 54lianxi** [comment]
@zhouteng0217 ,can you give me a answer

**Comment by zhouteng0217** [comment]
@54lianxi  我也尝试了下，在android系统里面，分享多张位于app内置存储的应用沙盒内(flutter代码的getApplicationDocumentsDirectory目录)下的图片到QQ时，容易出现这样的问题，我猜测可能是QQ的某些限制所致。

但是分享图库，或者外置存储里面的图片到qq时，却没有这样的问题，因此在demo里面，分享多图时，我将图片存储到外置存储的沙盒里面(也就是getExternalStorageDirectory目录)，再进行分享，发现基本上不会有这样的问题。

而且对于微信来说，不支持多图分享内置存储应用沙盒里面的图片。 所以建议，将图片，存储到外置存储目录下，再进行分享。
