### ISSUE TITLE
When I share a file twice, the file will be add the suffix ".octet-stream"

### ISSUE THREAD

**Issue by boring2** [zhouteng0217/ShareExtend#27]
I share a file(maybe named "file.md") to wechat,  the first share  I can get the correct result.

But when I share the file again, it will be  "file.md..octet-stream". 

And I also found the issue #26

**Comment by boring2** [comment]
And if I change the file name, for example, "file.md" to "file1.md", the "file1.md" can be shared correctly.

**Comment by zhouteng0217** [comment]
@boring2   自己人吧，那我就中文交流啦。 经过我测试，在android平台上，如果是分享app应用沙盒目录(对应flutter代码的getApplicationDocumentsDirectory目录)下的文件到微信，确实存在多次分享，会被微信重命名的问题，这个应该是微信的限制，分享到qq就没这个问题。

**Comment by boring2** [comment]
ok 因为不是什么大问题， 一直没理，目前改到了getExternalStorageDirectory, 可以分享多次~谢谢~

但是更新插件到1.1.5 依然存在 issue 26 报错. 虽然报错 但是可以分享。
