### ISSUE TITLE
missingplugin

### ISSUE THREAD

**Issue by avdisx** [zhouteng0217/ShareExtend#31]
hi i have a porblem.

D/jniPdfium(19205): Init FPDF library
D/EGL_emulation(19205): eglMakeCurrent: 0xd6a1a240: ver 3 1 (tinfo 0xd6a0f810)
E/flutter (19205): [ERROR:flutter/lib/ui/ui_dart_state.cc(157)] Unhandled Exception: MissingPluginException(No implementation found for method share on channel com.zt.shareextend/share_extend)
E/flutter (19205): #0      MethodChannel.invokeMethod 
package:flutter/…/services/platform_channel.dart:319
E/flutter (19205): <asynchronous suspension>
E/flutter (19205): #1      ShareExtend._shareInner  (package:share_extend/share_extend.dart:62:21)
E/flutter (19205): #2      ShareExtend.share  (package:share_extend/share_extend.dart:34:12)
E/flutter (19205): #3      _SonuclarPDFEkraniState.build.<anonymous closure> 
package:sis_av_hesaplama/screen/sonuc_pdfekrani.dart:103
E/flutter (19205): #4      _InkResponseState._handleTap 
package:flutter/…/material/ink_well.dart:706
E/flutter (19205): #5      _InkResponseState.build.<anonymous closure> 
package:flutter/…/material/ink_well.dart:789
E/flutter (19205): #6      GestureRecognizer.invokeCallback

**Comment by JEuler** [comment]
How you are using this package? Have you tried flutter clean to rebuild the app?

**Comment by avdisx** [comment]
yeah. Does the plugin not work on Android 6.0?

**Comment by JEuler** [comment]
Yes is should work, the min sdk for Android version is 16. 
Please provide your pubspec piece of code and the code where you use the ShareExtend.

**Comment by JEuler** [comment]
https://github.com/zhouteng0217/ShareExtend/issues/14 - please try this "solution"

**Comment by avdisx** [comment]
missing plugin solved. I wrote a title in the share code instead of the file type. Sorry. But android 6 not working. i want send mail for gmail. phone sad "permission denied for the attachment" i cant understand. thanks

**Comment by JEuler** [comment]
This is very strange, I've tried it on Android 6 emulator (don't have device) and sharing dialog appeared. Maybe this is some content provider error, please try this 
https://github.com/zhouteng0217/ShareExtend/issues/26#issuecomment-613983678

**Comment by avdisx** [comment]
yes. sharing dialog  appering. but attecment denided.
![Screenshot_1587203946](https://user-images.githubusercontent.com/55236238/79634656-91c4ba80-8174-11ea-8203-59cbe1e01139.png)
![Screenshot_1587203952](https://user-images.githubusercontent.com/55236238/79634659-9ab58c00-8174-11ea-8624-350330a7d143.png)

**Comment by zhouteng0217** [comment]
@avdisx , please try the version 1.1.5, the issue should be fixed.

**Comment by avdisx** [comment]
is not working. i am not send with whatsapp? why ? :D

**Comment by zhouteng0217** [comment]
@avdisx  I tested on emulator android 6  and it worked well.  Did you test with demo code on emulator android 6 ?

<img width="315" alt="WX20200424-085617@2x" src="https://user-images.githubusercontent.com/10185053/80164260-113a0a00-860b-11ea-9e65-5eff13683fa3.png">
<img width="319" alt="WX20200424-091126@2x" src="https://user-images.githubusercontent.com/10185053/80164443-8e657f00-860b-11ea-897f-08c3c7ba9bb1.png">

**Comment by avdisx** [comment]
Ok. thanks. its working but i not working in telegram. interesting :D thanks for everything :D 🥇
