### ISSUE TITLE
Share Panel title not working on Android

### ISSUE THREAD

**Issue by mbabuglia** [zhouteng0217/ShareExtend#36]
Version 1.1.15 on Android.

I am using share like this:
`ShareExtend.share(file.path, "file", sharePanelTitle: "Panel title", subject: "For email");`

Subject works fine, however share panel title is not displaying, what it is displayed is the file's path with strange characters, as seen in the image:

![WhatsApp Image 2020-04-30 at 3 05 46 PM](https://user-images.githubusercontent.com/26937885/80749175-735ba900-8afc-11ea-9cd6-92d0a0265d76.jpeg)

**Comment by allanwolski** [comment]
Same here

**Comment by zhouteng0217** [comment]
@mbabuglia  @allanwolski   This is an api provided by android, but may not work on some devices for its rom did not implement the function.
