### ISSUE TITLE
这个插件使用的分享图片实质是分享了文件出去。

### ISSUE THREAD

**Issue by ymwm-lxl** [zhouteng0217/ShareExtend#39]
希望能够有分享 base64image 的api

**Comment by zhouteng0217** [comment]
@ymwm-lxl  考虑到系统提供的api的方式，也是需要通过文件路径来分享的，如果提供base64的图片数据分享，估计也是先保存成图片，然后再分享出去。你可以先暂时在外面这样处理下，后面我考虑下，要不要封装到库里面去。

**Comment by ymwm-lxl** [comment]
不知道作者是否对该框架进行了优化，我已经通过自己学习开发了一个类似插件解决了这里的问题，所以关闭该问题
