### ISSUE TITLE
can't share text + image Android on whatsapp

### ISSUE THREAD

**Issue by peswanibros** [zhouteng0217/ShareExtend#46]
Only image getting shared. 

`    ShareExtend.share(file.path, 'this is my image', subject: "Hello");
`

there is no text when sharing.

I think there should be a line in `ShareExtendedPlugin.java` after line number 102

`shareIntent.putExtra(Intent.EXTRA_TEXT, type);`

**Comment by peswanibros** [comment]
I tested it it work now.

https://github.com/zhouteng0217/ShareExtend/pull/47

**Comment by zhouteng0217** [comment]
@peswanibros  Thanks for the pr, but we can't use the variable "type" here.  It was used to distinguish the type of sharing.
So I will add a new field "extraText" for this situation.

**Comment by peswanibros** [comment]
@zhouteng0217 Thanks. Looking forward to it.

**Comment by zhouteng0217** [comment]
@peswanibros  I added it on the new version 1.1.8. Please have a try.
