### ISSUE TITLE
Module 'share_extend' not found

### ISSUE THREAD

**Issue by bigzhu0608** [zhouteng0217/ShareExtend#48]
Launching lib/main.dart on iPhone 11 Pro Max in debug mode...
Running pod install...                                              1.0s
Running Xcode build...
Xcode build done.                                           14.6s
Failed to build iOS app
Error output from Xcode build:
↳
    ** BUILD FAILED **

Xcode's output:
↳
    error: the following command failed with exit code 0 but produced no further output
    CompileC /Users/bruce/Library/Developer/Xcode/DerivedData/Runner-cgopmhyxonoqgqbrncalhjmszkrs/Build/Intermediates.noindex/Pods.build/Debug-iphonesimulator/FMDB.build/Objects-normal/x86_64/FMDatabaseQueue.o /Users/bruce/Documents/work/esky/interference/ios/Pods/FMDB/src/fmdb/FMDatabaseQueue.m normal x86_64 objective-c com.apple.compilers.llvm.clang.1_0.compiler
    error: the following command failed with exit code 0 but produced no further output
    CompileC /Users/bruce/Library/Developer/Xcode/DerivedData/Runner-cgopmhyxonoqgqbrncalhjmszkrs/Build/Intermediates.noindex/Pods.build/Debug-iphonesimulator/FMDB.build/Objects-normal/x86_64/FMDatabase.o /Users/bruce/Documents/work/esky/interference/ios/Pods/FMDB/src/fmdb/FMDatabase.m normal x86_64 objective-c com.apple.compilers.llvm.clang.1_0.compiler
    /Users/bruce/.pub-cache/hosted/pub.flutter-io.cn/permission_handler-4.4.0+hotfix.4/ios/Classes/strategies/NotificationPermissionStrategy.m:71:5: warning: 'UIRemoteNotificationType' is deprecated: first deprecated in iOS 8.0 - Use UserNotifications Framework's UNAuthorizationOptions for user notifications and registerForRemoteNotifications for receiving remote notifications instead. [-Wdeprecated-declarations]
        UIRemoteNotificationType type = [[UIApplication sharedApplication] enabledRemoteNotificationTypes];
        ^
    In module 'UIKit' imported from /Users/bruce/Documents/work/esky/interference/ios/Pods/Target Support Files/permission_handler/permission_handler-prefix.pch:2:
    /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator13.2.sdk/System/Library/Frameworks/UIKit.framework/Headers/UIApplication.h:69:32: note: 'UIRemoteNotificationType' has been explicitly marked deprecated here
    typedef NS_OPTIONS(NSUInteger, UIRemoteNotificationType) {
                                   ^
    /Users/bruce/.pub-cache/hosted/pub.flutter-io.cn/permission_handler-4.4.0+hotfix.4/ios/Classes/strategies/NotificationPermissionStrategy.m:71:72: warning: 'enabledRemoteNotificationTypes' is deprecated: first deprecated in iOS 8.0 - Use -[UIApplication isRegisteredForRemoteNotifications] and UserNotifications Framework's -[UNUserNotificationCenter getNotificationSettingsWithCompletionHandler:] to retrieve user-enabled remote notification and user notification settings [-Wdeprecated-declarations]
        UIRemoteNotificationType type = [[UIApplication sharedApplication] enabledRemoteNotificationTypes];
                                                                           ^
    In module 'UIKit' imported from /Users/bruce/Documents/work/esky/interference/ios/Pods/Target Support Files/permission_handler/permission_handler-prefix.pch:2:
    /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator13.2.sdk/System/Library/Frameworks/UIKit.framework/Headers/UIApplication.h:229:1: note: 'enabledRemoteNotificationTypes' has been explicitly marked deprecated here
    - (UIRemoteNotificationType)enabledRemoteNotificationTypes API_DEPRECATED("Use -[UIApplication isRegisteredForRemoteNotifications] and UserNotifications Framework's -[UNUserNotificationCenter getNotificationSettingsWithCompletionHandler:] to retrieve user-enabled remote notification and user notification settings", ios(3.0, 8.0)) API_UNAVAILABLE(tvos);
    ^
    2 warnings generated.
    **/Users/bruce/Documents/work/esky/interference/ios/Runner/GeneratedPluginRegistrant.m:28:9: fatal error: module 'share_extend' not found**
    @import share_extend;
     ~~~~~~~^~~~~~~~~~~~
    1 error generated.
    note: Using new build system
    note: Planning build
    note: Constructing build description
    warning: The iOS Simulator deployment target 'IPHONEOS_DEPLOYMENT_TARGET' is set to 4.3, but the range of supported deployment target versions is 8.0 to 13.2.99. (in target 'FMDB' from project 'Pods')
    warning: Mapping architecture armv7 to i386. Ensure that this target's Architectures and Valid Architectures build settings are configured correctly for the iOS Simulator platform. (in target 'image_picker' from project 'Pods')
    warning: Mapping architecture arm64 to x86_64. Ensure that this target's Architectures and Valid Architectures build settings are configured correctly for the iOS Simulator platform. (in target 'image_picker' from project 'Pods')

Could not build the application for the simulator.
Error launching application on iPhone 11 Pro Max.



```
flutter doctor
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, v1.17.4, on Mac OS X 10.14.6 18G87, locale zh-Hans-CN)
 
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.3)
[✓] Xcode - develop for iOS and macOS (Xcode 11.3.1)
[✓] Android Studio (version 4.0)
[!] IntelliJ IDEA Ultimate Edition (version 2020.1.1)
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
[✓] VS Code (version 1.46.1)
[✓] Connected device (2 available)

! Doctor found issues in 1 category.

```

**Comment by zhengcan** [comment]
I have the same issue after the lib had been upgraded to 1.1.8
The issue is gone when I downgrade to 1.1.7

**Comment by zhouteng0217** [comment]
@zhengcan  @bigzhu0608  感谢两位的反馈，确实有这个问题，我在新发布的1.1.9版本中已经修复了该问题。再次感谢！
