### ISSUE TITLE
iOS app crashing when Save Image is selected

### ISSUE THREAD

**Issue by richgoldmd** [zhouteng0217/ShareExtend#6]
On an iOS device, the app crashes when I select Save Image - This is on the SImulator. When I select Shared Albums I get the shared albums dialog which seems fine. Just the "Save Image" link causes the app to crash.
No debug output. It just terminates.

**Comment by richgoldmd** [comment]
Tried this on the device too. Same thing.
Other forms of sharing images seem to work.
FYI my image in a PNG image, only about 140kb

**Comment by richgoldmd** [comment]
FYI I was able to solve this. 
In iOS it is required to add the following to the Info.plist file if you do not exclude "Save Image":
```
<key>NSPhotoLibraryAddUsageDescription</key>
<string>$(PRODUCT_NAME)</string>
```
Adding this to Info.plist solved it and it works great.

**Comment by zhouteng0217** [comment]
@richgoldmd  yes,  "NSPhotoLibraryAddUsageDescription" should be added to the info.plist for saving images to photo library. Thanks for your feedback.
