### ISSUE TITLE
how to share url?

### ISSUE THREAD

**Issue by qxwei** [zhouteng0217/ShareExtend#7]
how to share url? such as web page，intenet imge

**Comment by zhouteng0217** [comment]
@qxwei You can share url  just like sharing text.  For sharing web image, you can download it to local storage and share it.

**Comment by twovs** [comment]
but，it call the exception as：PlatformException(error, file not exists, null)

ShareExtend.share("share text", "这是个网址，分享出去会是什么样子？https://www.twovs.com/");
