### ISSUE TITLE
安卓发送结束后的“返回第三方工具“字样是可修改的吗？

### ISSUE THREAD

**Issue by linguitang** [zhouteng0217/ShareExtend#8]

**Comment by zhouteng0217** [comment]
@linguitang 老哥说的是分享到微信后，微信内弹框里面的按钮显示的"返回第三方工具"这个字样吧，我查了下，如果是接入了微信的SDK，设置好微信的appid后， 是会显示成"返回" + 你的app名字的，但是我这个只是一个通用的，调用系统分享的组件，没有接入微信这些sdk的，所以是没办法修改的。

**Comment by linguitang** [comment]
ok，谢谢
